name: 'macros'
version: '1.0.0'
config-version: 2

profile: 'macros'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  macros:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: view
